In [83]:
# PART 1 - Dataset Understanding (5 questions)
# 1.Import the pandas library.
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [84]:
# 2.Load the Dataset into a DataFrame .
import pandas as pd
df=pd.read_csv('/content/online_shopping_uncleaned_20000_rows (1).csv')

In [85]:
# 3. Display the First 10 Rows.
df.head()

,Unnamed: 0,CustomerID,Gender,Location,Tenure_Months,Transaction_ID,Transaction_Date,Product_SKU,Product_Description,Product_Category,...,Discount_pct,Payment_Status,Delivery_Days,Customer_Rating,Return_Status,Customer_City,Discount_Percent,Order_Priority,Support_Calls,Membership
0,0,17850.0,M,Chicago,12.0,16679.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,10.0,Pending,1,1.0,returned,Unknown,25%,High,3,Gold
1,1,17850.0,M,Chicago,12.0,16680.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,10.0,NaN,10days,NaN,NaN,NaN,25%,Medium,4calls,NaN
2,2,17850.0,M,Chicago,12.0,16696.0,2019-01-01,GGOENEBQ078999,Nest Cam Outdoor Security Camera - USA,Nest-USA,...,10.0,unknown,5,NaN,Returned,Mumbai,unknown,Medium,0,NaN
3,3,17850.0,M,Chicago,12.0,16699.0,2019-01-01,GGOENEBQ079099,Nest Protect Smoke + CO White Battery Alarm-USA,Nest-USA,...,10.0,Paid,1,3.0,returned,chennai,NaN,Low,3,Gold
4,4,17850.0,M,Chicago,12.0,16700.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,10.0,Pending,NaN,4.0,returned,chennai,15,NaN,NaN,Platinum

In [86]:
# 4.Display the Last 10 Rows
df.tail()

,Unnamed: 0,CustomerID,Gender,Location,Tenure_Months,Transaction_ID,Transaction_Date,Product_SKU,Product_Description,Product_Category,...,Discount_pct,Payment_Status,Delivery_Days,Customer_Rating,Return_Status,Customer_City,Discount_Percent,Order_Priority,Support_Calls,Membership
19995,19995,13854.0,F,Chicago,44.0,31174.0,2019-06-25,GGOEGFKA022299,Keyboard DOT Sticker,Office,...,30.0,unknown,1,NaN,returned,NaN,25%,High,4calls,NaN
19996,19996,13854.0,F,Chicago,44.0,31174.0,2019-06-25,GGOEGGOA017399,Maze Pen,Office,...,30.0,Paid,3,NaN,NaN,Unknown,unknown,NaN,2,gold
19997,19997,17790.0,F,Washington DC,34.0,31203.0,2019-06-25,GGOEYFKQ020699,YouTube Custom Decals,Office,...,30.0,paid,NaN,2.0,Not Returned,Mumbai,NaN,unknown,unknown,NaN
19998,19998,12370.0,F,New York,21.0,31175.0,2019-06-25,GGOEGFKQ020399,Google Laptop and Cell Phone Stickers,Office,...,30.0,Pending,7,NaN,returned,NaN,NaN,unknown,4calls,Gold
19999,19999,17404.0,F,New Jersey,11.0,31214.0,2019-06-25,GGOEGFKQ020399,Google Laptop and Cell Phone Stickers,Office,...,30.0,NaN,1,2.0,Not Returned,Chennai,NaN,Low,4calls,gold

In [87]:
# 5.Find thw total Number of Rows and Columns.
df.shape

(20000, 30)

In [88]:
# PART-2 Data Exploration(5 questions)
# 6. Display all Columns names
df.columns

Index(['Unnamed: 0', 'CustomerID', 'Gender', 'Location', 'Tenure_Months',
       'Transaction_ID', 'Transaction_Date', 'Product_SKU',
       'Product_Description', 'Product_Category', 'Quantity', 'Avg_Price',
       'Delivery_Charges', 'Coupon_Status', 'GST', 'Date', 'Offline_Spend',
       'Online_Spend', 'Month', 'Coupon_Code', 'Discount_pct',
       'Payment_Status', 'Delivery_Days', 'Customer_Rating', 'Return_Status',
       'Customer_City', 'Discount_Percent', 'Order_Priority', 'Support_Calls',
       'Membership'],
      dtype='object')

In [89]:
# 7. Check data type  od each columns
df.dtypes

Unnamed: 0               int64
CustomerID             float64
Gender                  object
Location                object
Tenure_Months          float64
Transaction_ID         float64
Transaction_Date        object
Product_SKU             object
Product_Description     object
Product_Category        object
Quantity               float64
Avg_Price              float64
Delivery_Charges       float64
Coupon_Status           object
GST                    float64
Date                    object
Offline_Spend          float64
Online_Spend           float64
Month                    int64
Coupon_Code             object
Discount_pct           float64
Payment_Status          object
Delivery_Days           object
Customer_Rating        float64
Return_Status           object
Customer_City           object
Discount_Percent        object
Order_Priority          object
Support_Calls           object
Membership              object
dtype: object

In [90]:
# 8.Display summary statistics
df.describe()

,Unnamed: 0,CustomerID,Tenure_Months,Transaction_ID,Quantity,Avg_Price,Delivery_Charges,GST,Offline_Spend,Online_Spend,Month,Discount_pct,Customer_Rating
count,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.00000,20000.000000,20000.000000,20000.000000,20000.000000,19917.000000,15012.000000
mean,9999.500000,15384.448800,26.419000,31757.398950,4.403900,56.511256,11.07499,0.134707,2998.910000,1960.758028,6.345150,22.944219,3.175793
std,5773.647028,1790.469818,13.522188,10442.150226,21.192688,63.316612,20.61016,0.044485,1116.007655,849.627815,3.993798,7.820770,1.338989
min,0.000000,12347.000000,2.000000,16679.000000,1.000000,0.390000,0.00000,0.050000,500.000000,320.250000,1.000000,10.000000,1.000000
25%,4999.750000,13819.000000,15.000000,22285.000000,1.000000,6.180000,6.00000,0.100000,2000.000000,1296.810000,3.000000,20.000000,2.000000
50%,9999.500000,15311.000000,27.000000,34498.500000,1.000000,19.190000,6.50000,0.100000,3000.000000,1918.530000,8.000000,20.000000,4.000000
75%,14999.250000,17114.000000,38.000000,36871.000000,2.000000,119.000000,6.50000,0.180000,4000.000000,2546.580000,8.000000,30.000000,4.000000
max,19999.000000,18260.000000,50.000000,48497.000000,825.000000,355.740000,521.36000,0.180000,5000.000000,4055.300000,12.000000,30.000000,5.000000

In [91]:
# 9.Count unique value in each colums
df.nunique()

Unnamed: 0             20000
CustomerID               889
Gender                     2
Location                   5
Tenure_Months             49
Transaction_ID         10153
Transaction_Date         154
Product_SKU             1012
Product_Description      385
Product_Category          20
Quantity                 111
Avg_Price                457
Delivery_Charges         185
Coupon_Status              3
GST                        4
Date                     154
Offline_Spend             11
Online_Spend             154
Month                      5
Coupon_Code                5
Discount_pct               3
Payment_Status             5
Delivery_Days              7
Customer_Rating            5
Return_Status              4
Customer_City              5
Discount_Percent           6
Order_Priority             5
Support_Calls              6
Membership                 4
dtype: int64

In [92]:
# 10. Identify columns with missing value .
df.isnull()

,Unnamed: 0,CustomerID,Gender,Location,Tenure_Months,Transaction_ID,Transaction_Date,Product_SKU,Product_Description,Product_Category,...,Discount_pct,Payment_Status,Delivery_Days,Customer_Rating,Return_Status,Customer_City,Discount_Percent,Order_Priority,Support_Calls,Membership
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,True,False,True,True,True,False,False,False,True
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,True
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,True,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,False,True,False,False,False,True
19996,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,True,False,False,True,False,False
19997,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,True,False,False,True
19998,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,False,True,True,False,False,False
19999,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,True,False,False,False

In [93]:
# PART-3 Missing value Handling(6 question)
# 11. Count missing value in each columns
df.isnull().sum()

Unnamed: 0                0
CustomerID                0
Gender                    0
Location                  0
Tenure_Months             0
Transaction_ID            0
Transaction_Date          0
Product_SKU               0
Product_Description       0
Product_Category          0
Quantity                  0
Avg_Price                 0
Delivery_Charges          0
Coupon_Status             0
GST                       0
Date                      0
Offline_Spend             0
Online_Spend              0
Month                     0
Coupon_Code            3356
Discount_pct             83
Payment_Status         3252
Delivery_Days          2395
Customer_Rating        4988
Return_Status          4076
Customer_City          3421
Discount_Percent       2849
Order_Priority         3356
Support_Calls          2856
Membership             6717
dtype: int64

In [94]:
# 12. Replace missing value in Customer_Rating with mean
df['Customer_Rating'].fillna(df['Customer_Rating'].mean(), inplace=True)

/tmp/ipykernel_1419/3844716144.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Customer_Rating'].fillna(df['Customer_Rating'].mean(), inplace=True)

In [95]:
# 13.	Replace missing values in Payment_Status with "Unknown".
df['Payment_Status'].fillna('Unknown',inplace=True)

/tmp/ipykernel_1419/1576518524.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Payment_Status'].fillna('Unknown',inplace=True)

In [96]:
#14.	Fill missing values in Delivery_Days using median.
df['Delivery_Days'].fillna(df['Delivery_Days'],inplace=True)

In [97]:
#15.	Replace missing Coupon_Code with "No Coupon".
df['Coupon_Code'].fillna('No Coupon',inplace=True)

/tmp/ipykernel_1419/640160943.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Coupon_Code'].fillna('No Coupon',inplace=True)

In [98]:
#16.	Verify that missing values are handled.
df.isnull().sum()

Unnamed: 0                0
CustomerID                0
Gender                    0
Location                  0
Tenure_Months             0
Transaction_ID            0
Transaction_Date          0
Product_SKU               0
Product_Description       0
Product_Category          0
Quantity                  0
Avg_Price                 0
Delivery_Charges          0
Coupon_Status             0
GST                       0
Date                      0
Offline_Spend             0
Online_Spend              0
Month                     0
Coupon_Code               0
Discount_pct             83
Payment_Status            0
Delivery_Days          2395
Customer_Rating           0
Return_Status          4076
Customer_City          3421
Discount_Percent       2849
Order_Priority         3356
Support_Calls          2856
Membership             6717
dtype: int64

In [99]:
#Part 4 – String Cleaning (6 Questions)
#17.	Remove leading and trailing spaces in all string columns.
df.columns.str.strip()

Index(['Unnamed: 0', 'CustomerID', 'Gender', 'Location', 'Tenure_Months',
       'Transaction_ID', 'Transaction_Date', 'Product_SKU',
       'Product_Description', 'Product_Category', 'Quantity', 'Avg_Price',
       'Delivery_Charges', 'Coupon_Status', 'GST', 'Date', 'Offline_Spend',
       'Online_Spend', 'Month', 'Coupon_Code', 'Discount_pct',
       'Payment_Status', 'Delivery_Days', 'Customer_Rating', 'Return_Status',
       'Customer_City', 'Discount_Percent', 'Order_Priority', 'Support_Calls',
       'Membership'],
      dtype='object')

In [100]:
#18.	Convert Payment_Status to lowercase.
df['Payment_Status'].str.lower()

0        pending
1        unknown
2        unknown
3           paid
4        pending
          ...
19995    unknown
19996       paid
19997      paid
19998    pending
19999    unknown
Name: Payment_Status, Length: 20000, dtype: object

In [101]:
#19.	Standardize values in Customer_City.
df['Customer_City'].str.lower()

0          unknown
1              NaN
2           mumbai
3         chennai
4         chennai
           ...
19995          NaN
19996      unknown
19997       mumbai
19998          NaN
19999      chennai
Name: Customer_City, Length: 20000, dtype: object

In [102]:
#20.	Clean Coupon_Code (remove extra spaces, make uppercase).
df['Coupon_Code'].str.upper()

0          UNKNOWN
1             NONE
2          NEWUSER
3          SALE20
4        NO COUPON
           ...
19995      UNKNOWN
19996    NO COUPON
19997      UNKNOWN
19998         NONE
19999      SALE20
Name: Coupon_Code, Length: 20000, dtype: object

In [103]:
#21.	Replace "unknown" values with NaN.
import numpy as np
df.replace('Unknown',np.nan,inplace=True)

In [104]:
#22.  " Replace NONE" and "none" with NaN.
df.replace(['NONE', 'none'], np.nan, inplace=True)

In [105]:
#Part 5 – Data Type Cleaning (6 Questions)
df['Delivery_Days'] = df['Delivery_Days'].str.replace('days', '')

In [106]:
#24.	Convert Discount_Percent to numeric (remove %).
df['Discount_Percent']=df['Discount_Percent'].str.replace('%', '')

In [107]:
#25.	Convert Support_Calls to numeric (remove "calls").
df['Support-Calls']=df['Support_Calls'].str.replace('calls', '')

In [108]:
#26.	Convert Customer_Rating to numeric.
df['Customer_Rating'] = pd.to_numeric(df['Customer_Rating'])

In [109]:
#27.	Handle invalid numeric values.
df['Customer_Rating'] = pd.to_numeric(df['Customer_Rating'], errors='coerce')

In [110]:
#28.	Verify updated data types.
df.info

<bound method DataFrame.info of        Unnamed: 0  CustomerID Gender       Location  Tenure_Months  \
0               0     17850.0      M        Chicago           12.0
1               1     17850.0      M        Chicago           12.0
2               2     17850.0      M        Chicago           12.0
3               3     17850.0      M        Chicago           12.0
4               4     17850.0      M        Chicago           12.0
...           ...         ...    ...            ...            ...
19995       19995     13854.0      F        Chicago           44.0
19996       19996     13854.0      F        Chicago           44.0
19997       19997     17790.0      F  Washington DC           34.0
19998       19998     12370.0      F       New York           21.0
19999       19999     17404.0      F     New Jersey           11.0

       Transaction_ID Transaction_Date     Product_SKU  \
0             16679.0       2019-01-01  GGOENEBJ079499
1             16680.0       2019-01-01  GGOENEBJ079499
2             16696.0       2019-01-01  GGOENEBQ078999
3             16699.0       2019-01-01  GGOENEBQ079099
4             16700.0       2019-01-01  GGOENEBJ079499
...               ...              ...             ...
19995         31174.0       2019-06-25  GGOEGFKA022299
19996         31174.0       2019-06-25  GGOEGGOA017399
19997         31203.0       2019-06-25  GGOEYFKQ020699
19998         31175.0       2019-06-25  GGOEGFKQ020399
19999         31214.0       2019-06-25  GGOEGFKQ020399

                                     Product_Description Product_Category  \
0      Nest Learning Thermostat 3rd Gen-USA - Stainle...         Nest-USA
1      Nest Learning Thermostat 3rd Gen-USA - Stainle...         Nest-USA
2                 Nest Cam Outdoor Security Camera - USA         Nest-USA
3        Nest Protect Smoke + CO White Battery Alarm-USA         Nest-USA
4      Nest Learning Thermostat 3rd Gen-USA - Stainle...         Nest-USA
...                                                  ...              ...
19995                               Keyboard DOT Sticker           Office
19996                                           Maze Pen           Office
19997                              YouTube Custom Decals           Office
19998              Google Laptop and Cell Phone Stickers           Office
19999              Google Laptop and Cell Phone Stickers           Office

       ...  Payment_Status  Delivery_Days  Customer_Rating Return_Status  \
0      ...         Pending              1         1.000000     returned
1      ...             NaN             10         3.175793           NaN
2      ...         unknown              5         3.175793      Returned
3      ...            Paid              1         3.000000     returned
4      ...         Pending            NaN         4.000000     returned
...    ...             ...            ...              ...           ...
19995  ...         unknown              1         3.175793     returned
19996  ...            Paid              3         3.175793           NaN
19997  ...           paid             NaN         2.000000  Not Returned
19998  ...         Pending              7         3.175793     returned
19999  ...             NaN              1         2.000000  Not Returned

       Customer_City Discount_Percent  Order_Priority  Support_Calls  \
0                NaN               25            High              3
1                NaN               25          Medium         4calls
2             Mumbai          unknown          Medium              0
3           chennai               NaN             Low              3
4           chennai                15             NaN            NaN
...              ...              ...             ...            ...
19995            NaN               25            High         4calls
19996            NaN          unknown             NaN              2
19997         Mumbai              NaN         unknown        unknown
19998            NaN              NaN         unknown         4calls
19999        Chennai              NaN             Low         4calls

       Membership Support-Calls
0            Gold             3
1             NaN             4
2             NaN             0
3            Gold             3
4        Platinum           NaN
...           ...           ...
19995         NaN             4
19996       gold              2
19997         NaN       unknown
19998        Gold             4
19999       gold              4

[20000 rows x 31 columns]>

In [111]:
#Part 6 – Duplicate Handling (4 Questions)
#29.	Check for duplicate rows.
df.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
19995    False
19996    False
19997    False
19998    False
19999    False
Length: 20000, dtype: bool

In [112]:
#30.	Count duplicate records.
df.duplicated().sum()

np.int64(0)

In [113]:
#31.	Remove duplicate rows.
df.drop_duplicates(inplace=True)

In [114]:
#32.	Display dataset shape after removal.
df.shape

(20000, 31)

In [115]:
#Part 7 – Order & Sales Analysis (6 Questions)
#33.	Count total number of orders.
len(df)

20000

In [116]:
#34.	Find number of orders by Payment_Status.
df['Payment_Status'].value_counts()

Payment_Status
FAILED     3430
 paid      3406
unknown    3354
Pending    3337
Paid       3221
Name: count, dtype: int64

In [117]:
#35.	Identify most common payment method/status.
df['Payment_Status'].mode()

0    FAILED
Name: Payment_Status, dtype: object

In [118]:
#36.	Find total number of returned orders.
df[df['Return_Status'] == 'Yes']

Empty DataFrame
Columns: [Unnamed: 0, CustomerID, Gender, Location, Tenure_Months, Transaction_ID, Transaction_Date, Product_SKU, Product_Description, Product_Category, Quantity, Avg_Price, Delivery_Charges, Coupon_Status, GST, Date, Offline_Spend, Online_Spend, Month, Coupon_Code, Discount_pct, Payment_Status, Delivery_Days, Customer_Rating, Return_Status, Customer_City, Discount_Percent, Order_Priority, Support_Calls, Membership, Support-Calls]
Index: []

[0 rows x 31 columns]

In [119]:
#37.	Calculate return percentage.
df['Return_Status'].value_counts(normalize=True)

Return_Status
 returned       0.336709
Not Returned    0.335527
Returned        0.327764
Name: proportion, dtype: float64

In [120]:
#38.	Count orders by Order_Priority.
df['Order_Priority'].value_counts()

Order_Priority
High       3396
unknown    3344
Low        3335
 high      3312
Medium     3257
Name: count, dtype: int64

In [121]:
#Part 8 – Customer Analysis (5 Questions)
#39.	Count number of customers by Customer_City.
df['Customer_City'].value_counts()

Customer_City
Mumbai       3403
Chennai      3315
Delhi        3284
 chennai     3265
Name: count, dtype: int64

In [122]:
#40.	Find city with highest orders.
df['Customer_City'].mode()

0    Mumbai
Name: Customer_City, dtype: object

In [123]:
#41.	Find average Customer_Rating.
df['Customer_Rating'].mean()

np.float64(3.175792699173994)

In [124]:
#42.	Identify customers with rating less than 3.
df[df['Customer_Rating']>300]

Empty DataFrame
Columns: [Unnamed: 0, CustomerID, Gender, Location, Tenure_Months, Transaction_ID, Transaction_Date, Product_SKU, Product_Description, Product_Category, Quantity, Avg_Price, Delivery_Charges, Coupon_Status, GST, Date, Offline_Spend, Online_Spend, Month, Coupon_Code, Discount_pct, Payment_Status, Delivery_Days, Customer_Rating, Return_Status, Customer_City, Discount_Percent, Order_Priority, Support_Calls, Membership, Support-Calls]
Index: []

[0 rows x 31 columns]

In [125]:
#43.	Count customers by Membership type.
df['Membership'].dtypes

dtype('O')

In [126]:
#Part 9 – Delivery Analysis (5 Questions)
#44.	Find average Delivery_Days.
df['Delivery_Days'] = pd.to_numeric(df['Delivery_Days'], errors='coerce')

In [127]:
#45.	Identify orders with delivery time > 7 days.
df[df['Delivery_Days']>7]

,Unnamed: 0,CustomerID,Gender,Location,Tenure_Months,Transaction_ID,Transaction_Date,Product_SKU,Product_Description,Product_Category,...,Payment_Status,Delivery_Days,Customer_Rating,Return_Status,Customer_City,Discount_Percent,Order_Priority,Support_Calls,Membership,Support-Calls
1,1,17850.0,M,Chicago,12.0,16680.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,NaN,10.0,3.175793,NaN,NaN,25,Medium,4calls,NaN,4
8,8,17850.0,M,Chicago,12.0,16704.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,NaN,10.0,4.000000,returned,Delhi,5,High,0,Platinum,0
9,9,17850.0,M,Chicago,12.0,16710.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,Paid,10.0,3.175793,Returned,Mumbai,5,unknown,NaN,Gold,NaN
18,18,17850.0,M,Chicago,12.0,16723.0,2019-01-01,GGOENEBQ078999,Nest Cam Outdoor Security Camera - USA,Nest-USA,...,unknown,10.0,4.000000,NaN,Delhi,25,High,unknown,gold,unknown
29,29,14688.0,F,New York,46.0,16732.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,Pending,10.0,1.000000,returned,Chennai,unknown,high,unknown,Gold,unknown
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19944,19944,13078.0,F,California,28.0,29486.0,2019-06-02,GGOEYOLR018699,YouTube Leatherette Notebook Combo,Office,...,NaN,10.0,3.175793,Not Returned,NaN,15,High,unknown,gold,unknown
19947,19947,17912.0,M,New Jersey,7.0,29415.0,2019-06-02,GGOEGGOA017399,Maze Pen,Office,...,unknown,10.0,3.000000,Returned,Chennai,unknown,NaN,NaN,Silver,NaN
19959,19959,12867.0,M,Chicago,32.0,29423.0,2019-06-02,GGOEGFKA022299,Keyboard DOT Sticker,Office,...,Paid,10.0,4.000000,returned,chennai,NaN,unknown,unknown,NaN,unknown
19967,19967,13846.0,F,New Jersey,4.0,29407.0,2019-06-02,GGOEGOAQ018099,Pen Pencil & Highlighter Set,Office,...,Pending,10.0,3.000000,Returned,Mumbai,NaN,High,unknown,Silver,unknown
19984,19984,15194.0,M,Chicago,33.0,30614.0,2019-06-17,GGOEGFKQ020399,Google Laptop and Cell Phone Stickers,Office,...,Pending,10.0,4.000000,returned,Mumbai,15,NaN,3,Platinum,3

In [128]:
#46.	Count delayed orders.
(df['Delivery_Days'] > 7)

0        False
1         True
2        False
3        False
4        False
         ...
19995    False
19996    False
19997    False
19998    False
19999    False
Name: Delivery_Days, Length: 20000, dtype: bool

In [129]:
#47.	Compare delivery time by Order_Priority.
Order_Priority=df.groupby('Order_Priority')['Delivery_Days'].mean()
print(Order_Priority)

Order_Priority
 high      4.559921
High       4.660594
Low        4.633186
Medium     4.657285
unknown    4.644612
Name: Delivery_Days, dtype: float64

In [130]:
#48.	Find fastest delivery category.
df.groupby('Order_Priority')['Delivery_Days'].min()

Order_Priority
 high      1.0
High       1.0
Low        1.0
Medium     1.0
unknown    1.0
Name: Delivery_Days, dtype: float64

In [131]:
#Part 10 – Discount & Coupon Analysis (5 Questions)
#49.	Find average Discount_Percent.
df['Discount_Percent'] = pd.to_numeric(df['Discount_Percent'], errors='coerce')

In [132]:
#50.	Identify orders with highest discount.
df['Discount_Percent'].max()

25.0

In [133]:
#51.	Count how many orders used coupons.
df['Coupon_Status'].count()

np.int64(20000)

In [134]:
#52.	Find most used Coupon_Code.
df['Coupon_Code'].value_counts().idxmax()

'unknown'

In [135]:
#53.	Compare price before and after discount (if available).
df['Discounted_Price'] = df['Avg_Price'] - (df['Avg_Price'] * df['Discount_pct'] / 100)

In [136]:
#Part 11 – Support & Service Analysis (4 Questions)
#54.	Find average Support_Calls per order.
df['Support_Calls'] = pd.to_numeric(
    df['Support_Calls'].str.replace('calls', '', case=False).str.strip(),
    errors='coerce'
)

In [137]:
#55.	Identify orders with more than 2 support calls.
df[df['Support_Calls']>2]

,Unnamed: 0,CustomerID,Gender,Location,Tenure_Months,Transaction_ID,Transaction_Date,Product_SKU,Product_Description,Product_Category,...,Delivery_Days,Customer_Rating,Return_Status,Customer_City,Discount_Percent,Order_Priority,Support_Calls,Membership,Support-Calls,Discounted_Price
0,0,17850.0,M,Chicago,12.0,16679.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,1.0,1.000000,returned,NaN,25.0,High,3.0,Gold,3,138.339
1,1,17850.0,M,Chicago,12.0,16680.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,10.0,3.175793,NaN,NaN,25.0,Medium,4.0,NaN,4,138.339
3,3,17850.0,M,Chicago,12.0,16699.0,2019-01-01,GGOENEBQ079099,Nest Protect Smoke + CO White Battery Alarm-USA,Nest-USA,...,1.0,3.000000,returned,chennai,NaN,Low,3.0,Gold,3,73.350
19,19,17850.0,M,Chicago,12.0,16724.0,2019-01-01,GGOENEBB078899,Nest Cam Indoor Security Camera - USA,Nest-USA,...,NaN,5.000000,NaN,NaN,5.0,High,3.0,Gold,3,110.493
22,22,17850.0,M,Chicago,12.0,16731.0,2019-01-01,GGOENEBQ078999,Nest Cam Outdoor Security Camera - USA,Nest-USA,...,2.0,3.000000,NaN,NaN,25.0,NaN,4.0,NaN,4,110.493
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19993,19993,16013.0,M,New York,31.0,31175.0,2019-06-25,GGOEAFKQ020599,Android Sticker Sheet Ultra Removable,Office,...,3.0,3.175793,NaN,NaN,5.0,Low,3.0,NaN,3,2.093
19994,19994,16013.0,M,New York,31.0,31175.0,2019-06-25,GGOEGFKA022299,Keyboard DOT Sticker,Office,...,7.0,3.175793,Not Returned,chennai,5.0,Low,3.0,gold,3,1.050
19995,19995,13854.0,F,Chicago,44.0,31174.0,2019-06-25,GGOEGFKA022299,Keyboard DOT Sticker,Office,...,1.0,3.175793,returned,NaN,25.0,High,4.0,NaN,4,1.050
19998,19998,12370.0,F,New York,21.0,31175.0,2019-06-25,GGOEGFKQ020399,Google Laptop and Cell Phone Stickers,Office,...,7.0,3.175793,returned,NaN,NaN,unknown,4.0,Gold,4,2.093
19999,19999,17404.0,F,New Jersey,11.0,31214.0,2019-06-25,GGOEGFKQ020399,Google Laptop and Cell Phone Stickers,Office,...,1.0,2.000000,Not Returned,Chennai,NaN,Low,4.0,gold,4,2.093

In [138]:
#56.	Find relation between Support_Calls and Return_Status.
df['Support_Calls'] = pd.to_numeric(df['Support_Calls'], errors='coerce')

In [139]:
#57.	Identify problematic orders (high calls + returns)
df[df['Support_Calls']>2]

,Unnamed: 0,CustomerID,Gender,Location,Tenure_Months,Transaction_ID,Transaction_Date,Product_SKU,Product_Description,Product_Category,...,Delivery_Days,Customer_Rating,Return_Status,Customer_City,Discount_Percent,Order_Priority,Support_Calls,Membership,Support-Calls,Discounted_Price
0,0,17850.0,M,Chicago,12.0,16679.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,1.0,1.000000,returned,NaN,25.0,High,3.0,Gold,3,138.339
1,1,17850.0,M,Chicago,12.0,16680.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,10.0,3.175793,NaN,NaN,25.0,Medium,4.0,NaN,4,138.339
3,3,17850.0,M,Chicago,12.0,16699.0,2019-01-01,GGOENEBQ079099,Nest Protect Smoke + CO White Battery Alarm-USA,Nest-USA,...,1.0,3.000000,returned,chennai,NaN,Low,3.0,Gold,3,73.350
19,19,17850.0,M,Chicago,12.0,16724.0,2019-01-01,GGOENEBB078899,Nest Cam Indoor Security Camera - USA,Nest-USA,...,NaN,5.000000,NaN,NaN,5.0,High,3.0,Gold,3,110.493
22,22,17850.0,M,Chicago,12.0,16731.0,2019-01-01,GGOENEBQ078999,Nest Cam Outdoor Security Camera - USA,Nest-USA,...,2.0,3.000000,NaN,NaN,25.0,NaN,4.0,NaN,4,110.493
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19993,19993,16013.0,M,New York,31.0,31175.0,2019-06-25,GGOEAFKQ020599,Android Sticker Sheet Ultra Removable,Office,...,3.0,3.175793,NaN,NaN,5.0,Low,3.0,NaN,3,2.093
19994,19994,16013.0,M,New York,31.0,31175.0,2019-06-25,GGOEGFKA022299,Keyboard DOT Sticker,Office,...,7.0,3.175793,Not Returned,chennai,5.0,Low,3.0,gold,3,1.050
19995,19995,13854.0,F,Chicago,44.0,31174.0,2019-06-25,GGOEGFKA022299,Keyboard DOT Sticker,Office,...,1.0,3.175793,returned,NaN,25.0,High,4.0,NaN,4,1.050
19998,19998,12370.0,F,New York,21.0,31175.0,2019-06-25,GGOEGFKQ020399,Google Laptop and Cell Phone Stickers,Office,...,7.0,3.175793,returned,NaN,NaN,unknown,4.0,Gold,4,2.093
19999,19999,17404.0,F,New Jersey,11.0,31214.0,2019-06-25,GGOEGFKQ020399,Google Laptop and Cell Phone Stickers,Office,...,1.0,2.000000,Not Returned,Chennai,NaN,Low,4.0,gold,4,2.093

In [140]:
#Part 12 – Final Output (4 Questions)
#58.	Save cleaned dataset as clean_online_shopping.csv.
df.to_csv('clean_online_shopping.csv', index=False)

In [141]:
#59.	Export analysis results to CSV.
df.to_csv('analysis_result.csv',index=False)

In [147]:
#60.	Display final dataset shape.
print("Final Dataset Shape:",df.shape)

Final Dataset Shape: (20000, 32)

In [148]:
# Identify problematic orders(high call + return).
problematic_orders=df[(df['Support_Calls']>2)&(df['Return_Status'] == 'Returned')]
print(problematic_orders)

       Unnamed: 0  CustomerID Gender    Location  Tenure_Months  \
24             24     13047.0      M  California           43.0
43             43     17511.0      F     Chicago           25.0
180           180     17920.0      F  California           18.0
212           212     14606.0      F     Chicago           33.0
239           239     15694.0      F    New York           41.0
...           ...         ...    ...         ...            ...
19943       19943     16817.0      M  California           20.0
19965       19965     13846.0      F  New Jersey            4.0
19974       19974     13846.0      F  New Jersey            4.0
19975       19975     13846.0      F  New Jersey            4.0
19985       19985     15194.0      M     Chicago           33.0

       Transaction_ID Transaction_Date     Product_SKU  \
24            16684.0       2019-01-01  GGOENEBQ079199
43            16826.0       2019-01-03  GGOENEBJ079499
180           17068.0       2019-01-04  GGOENEBQ079099
212           17970.0       2019-01-16  GGOENEBB078899
239           18013.0       2019-01-16  GGOENEBQ079199
...               ...              ...             ...
19943         29478.0       2019-06-02  GGOEYOLR018699
19965         29407.0       2019-06-02  GGOEGOAB021699
19974         29410.0       2019-06-02  GGOEAFKQ020599
19975         29411.0       2019-06-02  GGOEGOGA016299
19985         30614.0       2019-06-17  GGOEGGOA017399

                                     Product_Description Product_Category  \
24         Nest Protect Smoke + CO White Wired Alarm-USA         Nest-USA
43     Nest Learning Thermostat 3rd Gen-USA - Stainle...         Nest-USA
180      Nest Protect Smoke + CO White Battery Alarm-USA         Nest-USA
212                Nest Cam Indoor Security Camera - USA         Nest-USA
239        Nest Protect Smoke + CO White Wired Alarm-USA         Nest-USA
...                                                  ...              ...
19943                 YouTube Leatherette Notebook Combo           Office
19965                         Google Ballpoint Pen Black           Office
19974              Android Sticker Sheet Ultra Removable           Office
19975                        Grip Highlighter Pen 3 Pack           Office
19985                                           Maze Pen           Office

       ...  Delivery_Days  Customer_Rating  Return_Status Customer_City  \
24     ...            7.0         2.000000       Returned         Delhi
43     ...            2.0         3.175793       Returned           NaN
180    ...            2.0         4.000000       Returned         Delhi
212    ...           10.0         1.000000       Returned        Mumbai
239    ...            2.0         1.000000       Returned           NaN
...    ...            ...              ...            ...           ...
19943  ...            2.0         4.000000       Returned         Delhi
19965  ...            2.0         4.000000       Returned       Chennai
19974  ...            NaN         4.000000       Returned         Delhi
19975  ...            3.0         3.175793       Returned        Mumbai
19985  ...            7.0         2.000000       Returned        Mumbai

       Discount_Percent Order_Priority  Support_Calls  Membership  \
24                  5.0            Low            3.0    Platinum
43                 10.0            NaN            3.0         NaN
180                10.0        unknown            3.0         NaN
212                10.0          high             3.0        Gold
239                10.0          high             3.0       gold
...                 ...            ...            ...         ...
19943              10.0         Medium            3.0       gold
19965              15.0            NaN            4.0    Platinum
19974              10.0         Medium            3.0         NaN
19975               NaN         Medium            3.0        Gold
19985              10.0          high             3.0      Silver

       Support-Calls Discounted_Price
24                 3           73.350
43                 3          138.339
180                3           73.350
212                3          110.493
239                3           73.350
...              ...              ...
19943              3            4.893
19965              4            1.393
19974              3            2.093
19975              3            2.443
19985              3            0.553

[1074 rows x 32 columns]

In [149]:
# Save cleaned data set.
df.to_csv('/content/clean_online_shopping.csv',index=False)

In [150]:
#export analysis to csv.
df.to_csv('/content/analysis_result.csv',index=False)

In [151]:
#Display Final dataset shape
df.shape

(20000, 32)

In [152]:
from google.colab import files
files.download('/content/clean_online_shopping.csv')